// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.keyboardevent.keypress.hack.use_legacy_keycode_and_charcode", "powerpoint.officeapps.live.com");
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "1cea64ca-5c2a-415c-b1cf-8f4e8678973f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1553492647);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1553492767);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1553495767);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1553492407);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1553492287);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1553492527);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1553242524);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1553492887);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1553241654);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ef978051-84a1-4229-a2a4-386862c367ee}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1553439600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1553495829409");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1553497622409");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1553495743001");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1553499343001");
user_pref("browser.search.region", "JP");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190317215230");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1553495324");
user_pref("browser.slowStartup.averageTime", 696);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190317215230");
user_pref("browser.startup.homepage_override.mstone", "66.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1553241656537");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "008cf782f79f407d943fe3b0127bce96");
user_pref("extensions.blocklist.lastModified", "Thu, 21 Mar 2019 12:41:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1553492647);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190317215230");
user_pref("extensions.lastAppVersion", "66.0");
user_pref("extensions.lastPlatformVersion", "66.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{0f0e4a3d-7fa6-4e52-8e11-01718716b414}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5951596c-03b2-49a0-8226-4a5e823d3aca\",\"screenshots@mozilla.org\":\"c7db37a5-5546-435a-ba6d-9286431b6b75\",\"webcompat-reporter@mozilla.org\":\"2bf05b14-ab5f-4603-b15d-841a52da68a2\",\"webcompat@mozilla.org\":\"f8834f0c-4411-4169-9f66-423e65a4caac\",\"fxmonitor@mozilla.org\":\"6ea50d82-67e0-4d77-9235-7f5bdc1b0754\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1553495484);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1553241765);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190317215230");
user_pref("media.gmp-manager.lastCheck", 1553495403);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1553245553);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "44ec6ea7-f0d3-43da-bb10-60ccaa152f3f");
user_pref("security.sandbox.plugin.tempDirSuffix", "86176cbd-69b9-4436-bd19-ee1e3171a45e");
user_pref("services.blocklist.addons.checked", 1553492731);
user_pref("services.blocklist.gfx.checked", 1553492731);
user_pref("services.blocklist.onecrl.checked", 1553492731);
user_pref("services.blocklist.pinning.checked", 1553492731);
user_pref("services.blocklist.plugins.checked", 1553492731);
user_pref("services.settings.clock_skew_seconds", -205);
user_pref("services.settings.last_update_seconds", 1553492731);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1553492731);
user_pref("services.settings.main.language-dictionaries.last_check", 1553492731);
user_pref("services.settings.main.onboarding.last_check", 1553492731);
user_pref("services.settings.main.sites-classification.last_check", 1553492731);
user_pref("services.settings.main.tippytop.last_check", 1553492731);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1553245553);
user_pref("toolkit.startup.last_success", 1553495323);
user_pref("toolkit.telemetry.cachedClientID", "a3876853-968f-4989-9d27-a0a35826196f");
user_pref("toolkit.telemetry.previousBuildID", "20190317215230");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
